title: "Estrés Económico y Bienestar Psicológico en Latinoamérica (2"
description: "Dataset longitudinal (2000-2025) que examina la relación entre indicadores de estrés económico y salud mental en 21 países de América Latina e Iberia."
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/estres-economico-y-bienestar-psicologico-en-latinoamerica-2000-2025"
